name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
concurrency: production

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Configure sccache env var and set build profile to ephemeral build
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTFLAGS='--cfg profile=ephemeral-build'" >> $GITHUB_ENV

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Tag the repository
        id: tag
        run: |
          DATE_TAG=$(date +v%Y%m%d)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          FULL_TAG="${DATE_TAG}_${COMMIT_HASH}"
          echo "tag=$FULL_TAG" >> $GITHUB_OUTPUT
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git tag -a $FULL_TAG -m "Published version $FULL_TAG" ${GITHUB_SHA}
          git push origin $FULL_TAG
      - name: Build
        run: cargo build --verbose --target x86_64-pc-windows-gnu
      - name: Run tests
        run: cargo test --verbose
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: target/release/rust-playground.exe
